# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Important Terminal Commands:
#    conda env create -f environment.yml
#    conda activate uber-eta-prediction
#    conda env update -f environment.yml 
#    conda env export -n uber-eta-prediction > envname.yml
#    conda env remove -n uber-eta-prediction
#    conda env list
#    conda list
#  
# Alternative Using pip & virtual environments:
#  - Create empty virtual environment:
#      Mac:     python3 -m venv uber-eta-prediction
#      Windows: python -m venv uber-eta-prediction
#  - Activate env:
#      source uber-eta-prediction activate
#  - Adding packages from requirements.txt
#      Mac: where python
#      Windows: which python
#      path/to/python -m pip install 
#  - Freezing dependencies
#      pip freeze > requirements.txt

name: uber-eta-prediction
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.26.4
  - pandas==2.2.1
  - matplotlib
  - seaborn
  - plotly==5.19.0
  - scikit-learn==1.3.0
  - xgboost==2.0.3
  - jupyterlab
  - pip
  - pip:
      - pytimetk
      - streamlit==1.33.0
      - google-api-python-client 
      - PyYAML==6.0.1
      - watchdog
      - h2o==3.46.0.1

